#!/usr/bin/env bash
# Dev-only. Builds throwaway repositories in each state Repo Pulse handles and
# writes their real `git status --porcelain=v2 --branch` output and marker files
# to test/fixtures.ts. The plugin never runs this script.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
out="$here/fixtures.ts"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Isolate from the developer's git config and make commits deterministic.
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1
export GIT_AUTHOR_NAME=fixture GIT_AUTHOR_EMAIL=fixture@example.com
export GIT_COMMITTER_NAME=fixture GIT_COMMITTER_EMAIL=fixture@example.com
export GIT_AUTHOR_DATE='2026-01-01T00:00:00Z' GIT_COMMITTER_DATE='2026-01-01T00:00:00Z'

g() { git -c init.defaultBranch=main -c advice.detachedHead=false -c merge.conflictStyle=merge "$@"; }
exists() { if [ -e "$1" ]; then echo true; else echo false; fi; }

capture() {
  local name=$1 dir=$2 gd status
  gd="$(g -C "$dir" rev-parse --absolute-git-dir)"
  status="$(g -C "$dir" --no-optional-locks status --porcelain=v2 --branch)"
  printf '  %s: {\n    status: %s,\n    markers: { mergeHead: %s, rebaseMerge: %s, rebaseApply: %s },\n  },\n' \
    "$name" "$(printf '%s\n' "$status" | jq -Rs .)" \
    "$(exists "$gd/MERGE_HEAD")" "$(exists "$gd/rebase-merge")" "$(exists "$gd/rebase-apply")" >> "$out"
}

# Clone the shared origin into a fresh working copy that tracks origin/main.
fresh() { g clone -q "$tmp/origin.git" "$tmp/$1"; }

# A file both sides of a merge or rebase change, to force a conflict.
diverge() {
  local d=$1
  g -C "$d" checkout -qb side
  echo side > "$d/a.txt"; g -C "$d" commit -qam side
  g -C "$d" checkout -q main
  echo main > "$d/a.txt"; g -C "$d" commit -qam main
}

cat > "$out" <<'EOF'
// Generated by test/capture-fixtures.sh. Do not edit by hand.
export type Fixture = { status: string; markers: { mergeHead: boolean; rebaseMerge: boolean; rebaseApply: boolean } }
export const fixtures: Record<string, Fixture> = {
EOF

g init -q --bare "$tmp/origin.git"
g clone -q "$tmp/origin.git" "$tmp/seed" 2>/dev/null
echo one > "$tmp/seed/a.txt"; echo x > "$tmp/seed/b.txt"
g -C "$tmp/seed" add .; g -C "$tmp/seed" commit -qm one; g -C "$tmp/seed" push -q -u origin main

# Cloned before origin moves, so it ends up behind.
fresh ahead_behind

fresh clean
capture clean "$tmp/clean"

fresh dirty
echo changed >> "$tmp/dirty/a.txt"
echo staged > "$tmp/dirty/b.txt"; g -C "$tmp/dirty" add b.txt
echo new > "$tmp/dirty/new.txt"
capture dirty "$tmp/dirty"

fresh untracked
echo new > "$tmp/untracked/new.txt"
capture untracked "$tmp/untracked"

fresh rename
g -C "$tmp/rename" mv b.txt c.txt
capture rename "$tmp/rename"

# Move origin two commits ahead, then make one local commit and fetch.
echo two > "$tmp/seed/b.txt"; g -C "$tmp/seed" commit -qam two
echo three > "$tmp/seed/b.txt"; g -C "$tmp/seed" commit -qam three
g -C "$tmp/seed" push -q
echo local > "$tmp/ahead_behind/c.txt"; g -C "$tmp/ahead_behind" add c.txt; g -C "$tmp/ahead_behind" commit -qm local
g -C "$tmp/ahead_behind" fetch -q
capture ahead_behind "$tmp/ahead_behind"

fresh no_upstream
g -C "$tmp/no_upstream" checkout -qb feature
capture no_upstream "$tmp/no_upstream"

fresh detached
g -C "$tmp/detached" checkout -q --detach
capture detached "$tmp/detached"

g init -q "$tmp/initial"
capture initial "$tmp/initial"

fresh merge_conflict
diverge "$tmp/merge_conflict"
g -C "$tmp/merge_conflict" merge -q side >/dev/null 2>&1 || true
capture merge_conflict "$tmp/merge_conflict"

fresh rebase_conflict
diverge "$tmp/rebase_conflict"
g -C "$tmp/rebase_conflict" checkout -q side
g -C "$tmp/rebase_conflict" rebase main >/dev/null 2>&1 || true
capture rebase_conflict "$tmp/rebase_conflict"

echo '}' >> "$out"
echo "wrote $out"
