// Generated by test/capture-fixtures.sh. Do not edit by hand.
export type Fixture = { status: string; markers: { mergeHead: boolean; rebaseMerge: boolean; rebaseApply: boolean } }
export const fixtures: Record<string, Fixture> = {
  clean: {
    status: "# branch.oid ff3287d8f6219545782cd9310a8ece24ac666d26\n# branch.head main\n# branch.upstream origin/main\n# branch.ab +0 -0\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  dirty: {
    status: "# branch.oid ff3287d8f6219545782cd9310a8ece24ac666d26\n# branch.head main\n# branch.upstream origin/main\n# branch.ab +0 -0\n1 .M N... 100644 100644 100644 5626abf0f72e58d7a153368ba57db4c673c0e171 5626abf0f72e58d7a153368ba57db4c673c0e171 a.txt\n1 M. N... 100644 100644 100644 587be6b4c3f93f93c489c0111bba5596147a26cb 19d9cc8584ac2c7dcf57d2680375e80f099dc481 b.txt\n? new.txt\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  untracked: {
    status: "# branch.oid ff3287d8f6219545782cd9310a8ece24ac666d26\n# branch.head main\n# branch.upstream origin/main\n# branch.ab +0 -0\n? new.txt\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  rename: {
    status: "# branch.oid ff3287d8f6219545782cd9310a8ece24ac666d26\n# branch.head main\n# branch.upstream origin/main\n# branch.ab +0 -0\n2 R. N... 100644 100644 100644 587be6b4c3f93f93c489c0111bba5596147a26cb 587be6b4c3f93f93c489c0111bba5596147a26cb R100 c.txt\tb.txt\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  ahead_behind: {
    status: "# branch.oid 1bef9944bbc80f554715d8cd688ebbac289023ec\n# branch.head main\n# branch.upstream origin/main\n# branch.ab +1 -2\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  no_upstream: {
    status: "# branch.oid 1a48262a9d534d17dcdb56e84fe5e9dda8482564\n# branch.head feature\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  detached: {
    status: "# branch.oid 1a48262a9d534d17dcdb56e84fe5e9dda8482564\n# branch.head (detached)\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  initial: {
    status: "# branch.oid (initial)\n# branch.head main\n",
    markers: { mergeHead: false, rebaseMerge: false, rebaseApply: false },
  },
  merge_conflict: {
    status: "# branch.oid 9b537d17397727fb828b033b2afec0cce236eb4c\n# branch.head main\n# branch.upstream origin/main\n# branch.ab +1 -0\nu UU N... 100644 100644 100644 100644 5626abf0f72e58d7a153368ba57db4c673c0e171 ba2906d0666cf726c7eaadd2cd3db615dedfdf3a 2299c37978265a95cbe835a4b0f0bbf15aad5549 a.txt\n",
    markers: { mergeHead: true, rebaseMerge: false, rebaseApply: false },
  },
  rebase_conflict: {
    status: "# branch.oid 9b537d17397727fb828b033b2afec0cce236eb4c\n# branch.head (detached)\nu UU N... 100644 100644 100644 100644 5626abf0f72e58d7a153368ba57db4c673c0e171 ba2906d0666cf726c7eaadd2cd3db615dedfdf3a 2299c37978265a95cbe835a4b0f0bbf15aad5549 a.txt\n",
    markers: { mergeHead: false, rebaseMerge: true, rebaseApply: false },
  },
}
